version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          working_directory: ./submission-app
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          working_directory: ./submission-app
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          working_directory: ./submission-app
          name: Install npm 
          command:  npm install
      - save_cache:
          working_directory: ./submission-app
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
