version: 2.1

jobs:
  build:
    working_directory: ./submission-app
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm 
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    working_directory: ./submission-app
    steps:
      - run:
          name: Test app
          command: npm test -- --coverage
# command: |
#- npm install -g codeclimate-test-reporter
#- codeclimate-test-reporter < coverage/lcov.info
