version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "submission-app/package.json" }}
      - run:
          name: Yarn
          working_directory: ./submission-app
          command:  yarn
      - run:
          name: Test
          working_directory: ./submission-app
          command:  yarn test
      - run:
          name: Report Test Coverage
          working_directory: ./submission-app
          command:  npm install -g codeclimate-test-reporter ; codeclimate-test-reporter < coverage/lcov.info
      - save_cache:
          working_directory: ./submission-app
          key: dependency-cache-{{ checksum "submission-app/package.json" }}
          paths:
            - node_modules
