version: 2.1

machine: &machine
  working_directory: ~/submission-app
  node:
    version: 8.9.4

jobs:
  test:
    steps:
      - run:
        name: Test run for Submission App
        command: npm test -- --coverage
#- npm install -g codeclimate-test-reporter
#- codeclimate-test-reporter < coverage/lcov.info
