version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "submission-app/package.json" }}
      - run:
          name: Yarn
          working_directory: ./submission-app
          command:  yarn
      - run:
          name: Test
          working_directory: ./submission-app
          command:  yarn test
      - codecov/upload:
          file: "submission-app/coverage"
      - save_cache:
          working_directory: ./submission-app
          key: dependency-cache-{{ checksum "submission-app/package.json" }}
          paths:
            - node_modules
