version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "submission-app/package.json" }}
      - run:
          name: Install npm 
          working_directory: ./submission-app
          command:  npm install
      - save_cache:
          working_directory: ./submission-app
          key: dependency-cache-{{ checksum "submission-app/package.json" }}
          paths:
            - node_modules
